-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\newsimul\Subsystem_ip_src_Channelizer.vhd
-- Created: 2023-04-25 13:19:39
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem_ip_src_Channelizer
-- Source Path: newsimul/Subsystem/Subsystem/Channelizer
-- Hierarchy Level: 2
-- 
-- HDLChannelizer
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Subsystem_ip_src_Subsystem_pkg.ALL;

ENTITY Subsystem_ip_src_Channelizer IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_32_0                        :   IN    std_logic;
        dataIn_re                         :   IN    vector_of_std_logic_vector16(0 TO 31);  -- sfix16_En15 [32]
        dataIn_im                         :   IN    vector_of_std_logic_vector16(0 TO 31);  -- sfix16_En15 [32]
        validIn                           :   IN    std_logic;
        dataOut_re                        :   OUT   vector_of_std_logic_vector16(0 TO 31);  -- sfix16_En15 [32]
        dataOut_im                        :   OUT   vector_of_std_logic_vector16(0 TO 31)  -- sfix16_En15 [32]
        );
END Subsystem_ip_src_Channelizer;


ARCHITECTURE rtl OF Subsystem_ip_src_Channelizer IS

  -- Component Declarations
  COMPONENT Subsystem_ip_src_FilterBank
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_32_0                      :   IN    std_logic;
          dataIn_re                       :   IN    vector_of_std_logic_vector16(0 TO 31);  -- sfix16_En15 [32]
          dataIn_im                       :   IN    vector_of_std_logic_vector16(0 TO 31);  -- sfix16_En15 [32]
          validIn                         :   IN    std_logic;
          filterOut_re                    :   OUT   vector_of_std_logic_vector16(0 TO 31);  -- sfix16_En15 [32]
          filterOut_im                    :   OUT   vector_of_std_logic_vector16(0 TO 31);  -- sfix16_En15 [32]
          filterOut_vld                   :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT Subsystem_ip_src_FFT
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_32_0                      :   IN    std_logic;
          filterOut_re                    :   IN    vector_of_std_logic_vector16(0 TO 31);  -- sfix16_En15 [32]
          filterOut_im                    :   IN    vector_of_std_logic_vector16(0 TO 31);  -- sfix16_En15 [32]
          filterOut_vld                   :   IN    std_logic;
          dataOut_re                      :   OUT   vector_of_std_logic_vector16(0 TO 31);  -- sfix16_En15 [32]
          dataOut_im                      :   OUT   vector_of_std_logic_vector16(0 TO 31)  -- sfix16_En15 [32]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Subsystem_ip_src_FilterBank
    USE ENTITY work.Subsystem_ip_src_FilterBank(rtl);

  FOR ALL : Subsystem_ip_src_FFT
    USE ENTITY work.Subsystem_ip_src_FFT(rtl);

  -- Signals
  SIGNAL filterOut_re                     : vector_of_std_logic_vector16(0 TO 31);  -- ufix16 [32]
  SIGNAL filterOut_im                     : vector_of_std_logic_vector16(0 TO 31);  -- ufix16 [32]
  SIGNAL filterOut_vld                    : std_logic;
  SIGNAL dataOut_re_tmp                   : vector_of_std_logic_vector16(0 TO 31);  -- ufix16 [32]
  SIGNAL dataOut_im_tmp                   : vector_of_std_logic_vector16(0 TO 31);  -- ufix16 [32]

BEGIN
  u_FilterBank : Subsystem_ip_src_FilterBank
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_32_0 => enb_1_32_0,
              dataIn_re => dataIn_re,  -- sfix16_En15 [32]
              dataIn_im => dataIn_im,  -- sfix16_En15 [32]
              validIn => validIn,
              filterOut_re => filterOut_re,  -- sfix16_En15 [32]
              filterOut_im => filterOut_im,  -- sfix16_En15 [32]
              filterOut_vld => filterOut_vld
              );

  u_FFT : Subsystem_ip_src_FFT
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_32_0 => enb_1_32_0,
              filterOut_re => filterOut_re,  -- sfix16_En15 [32]
              filterOut_im => filterOut_im,  -- sfix16_En15 [32]
              filterOut_vld => filterOut_vld,
              dataOut_re => dataOut_re_tmp,  -- sfix16_En15 [32]
              dataOut_im => dataOut_im_tmp  -- sfix16_En15 [32]
              );

  dataOut_re <= dataOut_re_tmp;

  dataOut_im <= dataOut_im_tmp;

END rtl;

