-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\newsimul\Subsystem_ip_src_HDL_CMA_core.vhd
-- Created: 2023-04-25 13:19:39
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem_ip_src_HDL_CMA_core
-- Source Path: newsimul/Subsystem/Subsystem1/HDL_CMA_core
-- Hierarchy Level: 2
-- 
-- Complex to Magnitude-Angle
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Subsystem_ip_src_Subsystem_pkg.ALL;

ENTITY Subsystem_ip_src_HDL_CMA_core IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In_re                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        In_im                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        validIn                           :   IN    std_logic;
        magnitude                         :   OUT   std_logic_vector(16 DOWNTO 0);  -- sfix17_En15
        angle                             :   OUT   std_logic_vector(18 DOWNTO 0);  -- sfix19_En16
        validOut                          :   OUT   std_logic
        );
END Subsystem_ip_src_HDL_CMA_core;


ARCHITECTURE rtl OF Subsystem_ip_src_HDL_CMA_core IS

  -- Component Declarations
  COMPONENT Subsystem_ip_src_Quadrant_Mapper
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          xin                             :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En15
          yin                             :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En15
          xout                            :   OUT   std_logic_vector(16 DOWNTO 0);  -- sfix17_En15
          yout                            :   OUT   std_logic_vector(16 DOWNTO 0);  -- sfix17_En15
          QA_Control                      :   OUT   std_logic_vector(2 DOWNTO 0)  -- ufix3
          );
  END COMPONENT;

  COMPONENT Subsystem_ip_src_CordicKernelMag
    PORT( xin                             :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En15
          yin                             :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En15
          zin                             :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En16
          lut_value                       :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
          idx                             :   IN    std_logic_vector(4 DOWNTO 0);  -- ufix5
          xout                            :   OUT   std_logic_vector(16 DOWNTO 0);  -- sfix17_En15
          yout                            :   OUT   std_logic_vector(16 DOWNTO 0);  -- sfix17_En15
          zout                            :   OUT   std_logic_vector(16 DOWNTO 0)  -- sfix17_En16
          );
  END COMPONENT;

  COMPONENT Subsystem_ip_src_Quadrant_Correction
    PORT( zin                             :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En16
          QA_Control                      :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
          zout                            :   OUT   std_logic_vector(18 DOWNTO 0)  -- sfix19_En16
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Subsystem_ip_src_Quadrant_Mapper
    USE ENTITY work.Subsystem_ip_src_Quadrant_Mapper(rtl);

  FOR ALL : Subsystem_ip_src_CordicKernelMag
    USE ENTITY work.Subsystem_ip_src_CordicKernelMag(rtl);

  FOR ALL : Subsystem_ip_src_Quadrant_Correction
    USE ENTITY work.Subsystem_ip_src_Quadrant_Correction(rtl);

  -- Signals
  SIGNAL Delay_ValidIn_reg                : std_logic_vector(0 TO 17);  -- ufix1 [18]
  SIGNAL ValidOutDelayed                  : std_logic;
  SIGNAL reset_outval                     : std_logic;
  SIGNAL In_re_signed                     : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL In_im_signed                     : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL qMapReal                         : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL qMapImag                         : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL In1Register                      : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL In2Register                      : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL XQMapped                         : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL yQMapped                         : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL ControlQC                        : std_logic_vector(2 DOWNTO 0);  -- ufix3
  SIGNAL XQMapped_signed                  : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yQMapped_signed                  : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL xin1                             : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yin1                             : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zin1                             : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL lut_value1                       : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL shift1                           : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL xout1                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL yout1                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL zout1                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL xout1_signed                     : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yout1_signed                     : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zout1_signed                     : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL xin2                             : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yin2                             : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zin2                             : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL lut_value2                       : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL shift2                           : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL xout2                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL yout2                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL zout2                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL xout2_signed                     : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yout2_signed                     : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zout2_signed                     : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL xin3                             : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yin3                             : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zin3                             : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL lut_value3                       : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL shift3                           : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL xout3                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL yout3                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL zout3                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL xout3_signed                     : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yout3_signed                     : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zout3_signed                     : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL xin4                             : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yin4                             : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zin4                             : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL lut_value4                       : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL shift4                           : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL xout4                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL yout4                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL zout4                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL xout4_signed                     : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yout4_signed                     : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zout4_signed                     : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL xin5                             : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yin5                             : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zin5                             : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL lut_value5                       : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL shift5                           : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL xout5                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL yout5                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL zout5                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL xout5_signed                     : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yout5_signed                     : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zout5_signed                     : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL xin6                             : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yin6                             : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zin6                             : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL lut_value6                       : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL shift6                           : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL xout6                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL yout6                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL zout6                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL xout6_signed                     : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yout6_signed                     : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zout6_signed                     : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL xin7                             : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yin7                             : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zin7                             : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL lut_value7                       : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL shift7                           : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL xout7                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL yout7                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL zout7                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL xout7_signed                     : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yout7_signed                     : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zout7_signed                     : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL xin8                             : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yin8                             : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zin8                             : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL lut_value8                       : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL shift8                           : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL xout8                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL yout8                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL zout8                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL xout8_signed                     : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yout8_signed                     : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zout8_signed                     : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL xin9                             : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yin9                             : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zin9                             : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL lut_value9                       : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL shift9                           : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL xout9                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL yout9                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL zout9                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL xout9_signed                     : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yout9_signed                     : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zout9_signed                     : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL xin10                            : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yin10                            : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zin10                            : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL lut_value10                      : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL shift10                          : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL xout10                           : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL yout10                           : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL zout10                           : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL xout10_signed                    : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yout10_signed                    : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zout10_signed                    : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL xin11                            : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yin11                            : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zin11                            : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL lut_value11                      : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL shift11                          : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL xout11                           : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL yout11                           : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL zout11                           : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL xout11_signed                    : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yout11_signed                    : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zout11_signed                    : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL xin12                            : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yin12                            : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zin12                            : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL lut_value12                      : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL shift12                          : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL xout12                           : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL yout12                           : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL zout12                           : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL xout12_signed                    : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yout12_signed                    : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zout12_signed                    : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL xin13                            : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yin13                            : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zin13                            : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL lut_value13                      : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL shift13                          : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL xout13                           : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL yout13                           : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL zout13                           : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL xout13_signed                    : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yout13_signed                    : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zout13_signed                    : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL xin14                            : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yin14                            : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zin14                            : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL lut_value14                      : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL shift14                          : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL xout14                           : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL yout14                           : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL zout14                           : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL xout14_signed                    : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yout14_signed                    : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zout14_signed                    : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL xin15                            : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL yin15                            : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zin15                            : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL lut_value15                      : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL shift15                          : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL xout15                           : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL yout15deadOut                    : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL zout15                           : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL xout15_signed                    : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL xin16                            : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL CSD_Gain_Factor_mul_temp         : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL CSD_Gain_Factor_cast             : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL xoutscaled                       : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zeroC                            : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL outSwitchMag                     : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL xin17                            : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL zout15_signed                    : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL ControlQC_unsigned               : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL zin16                            : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL DelayQC_Control_reg              : vector_of_unsigned3(0 TO 15);  -- ufix3 [16]
  SIGNAL ControlQCDelay                   : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL zout_corrected                   : std_logic_vector(18 DOWNTO 0);  -- ufix19
  SIGNAL zout_corrected_signed            : signed(18 DOWNTO 0);  -- sfix19_En16
  SIGNAL zeroCA                           : signed(18 DOWNTO 0);  -- sfix19_En16
  SIGNAL outSwitchAng                     : signed(18 DOWNTO 0);  -- sfix19_En16
  SIGNAL zout_corrected_1                 : signed(18 DOWNTO 0);  -- sfix19_En16

BEGIN
  u_QuadrantMapper : Subsystem_ip_src_Quadrant_Mapper
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              xin => std_logic_vector(In1Register),  -- sfix17_En15
              yin => std_logic_vector(In2Register),  -- sfix17_En15
              xout => XQMapped,  -- sfix17_En15
              yout => yQMapped,  -- sfix17_En15
              QA_Control => ControlQC  -- ufix3
              );

  u_Iteration : Subsystem_ip_src_CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin1),  -- sfix17_En15
              yin => std_logic_vector(yin1),  -- sfix17_En15
              zin => std_logic_vector(zin1),  -- sfix17_En16
              lut_value => std_logic_vector(lut_value1),  -- ufix16_En16
              idx => std_logic_vector(shift1),  -- ufix5
              xout => xout1,  -- sfix17_En15
              yout => yout1,  -- sfix17_En15
              zout => zout1  -- sfix17_En16
              );

  u_Iteration_1 : Subsystem_ip_src_CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin2),  -- sfix17_En15
              yin => std_logic_vector(yin2),  -- sfix17_En15
              zin => std_logic_vector(zin2),  -- sfix17_En16
              lut_value => std_logic_vector(lut_value2),  -- ufix16_En16
              idx => std_logic_vector(shift2),  -- ufix5
              xout => xout2,  -- sfix17_En15
              yout => yout2,  -- sfix17_En15
              zout => zout2  -- sfix17_En16
              );

  u_Iteration_2 : Subsystem_ip_src_CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin3),  -- sfix17_En15
              yin => std_logic_vector(yin3),  -- sfix17_En15
              zin => std_logic_vector(zin3),  -- sfix17_En16
              lut_value => std_logic_vector(lut_value3),  -- ufix16_En16
              idx => std_logic_vector(shift3),  -- ufix5
              xout => xout3,  -- sfix17_En15
              yout => yout3,  -- sfix17_En15
              zout => zout3  -- sfix17_En16
              );

  u_Iteration_3 : Subsystem_ip_src_CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin4),  -- sfix17_En15
              yin => std_logic_vector(yin4),  -- sfix17_En15
              zin => std_logic_vector(zin4),  -- sfix17_En16
              lut_value => std_logic_vector(lut_value4),  -- ufix16_En16
              idx => std_logic_vector(shift4),  -- ufix5
              xout => xout4,  -- sfix17_En15
              yout => yout4,  -- sfix17_En15
              zout => zout4  -- sfix17_En16
              );

  u_Iteration_4 : Subsystem_ip_src_CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin5),  -- sfix17_En15
              yin => std_logic_vector(yin5),  -- sfix17_En15
              zin => std_logic_vector(zin5),  -- sfix17_En16
              lut_value => std_logic_vector(lut_value5),  -- ufix16_En16
              idx => std_logic_vector(shift5),  -- ufix5
              xout => xout5,  -- sfix17_En15
              yout => yout5,  -- sfix17_En15
              zout => zout5  -- sfix17_En16
              );

  u_Iteration_5 : Subsystem_ip_src_CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin6),  -- sfix17_En15
              yin => std_logic_vector(yin6),  -- sfix17_En15
              zin => std_logic_vector(zin6),  -- sfix17_En16
              lut_value => std_logic_vector(lut_value6),  -- ufix16_En16
              idx => std_logic_vector(shift6),  -- ufix5
              xout => xout6,  -- sfix17_En15
              yout => yout6,  -- sfix17_En15
              zout => zout6  -- sfix17_En16
              );

  u_Iteration_6 : Subsystem_ip_src_CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin7),  -- sfix17_En15
              yin => std_logic_vector(yin7),  -- sfix17_En15
              zin => std_logic_vector(zin7),  -- sfix17_En16
              lut_value => std_logic_vector(lut_value7),  -- ufix16_En16
              idx => std_logic_vector(shift7),  -- ufix5
              xout => xout7,  -- sfix17_En15
              yout => yout7,  -- sfix17_En15
              zout => zout7  -- sfix17_En16
              );

  u_Iteration_7 : Subsystem_ip_src_CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin8),  -- sfix17_En15
              yin => std_logic_vector(yin8),  -- sfix17_En15
              zin => std_logic_vector(zin8),  -- sfix17_En16
              lut_value => std_logic_vector(lut_value8),  -- ufix16_En16
              idx => std_logic_vector(shift8),  -- ufix5
              xout => xout8,  -- sfix17_En15
              yout => yout8,  -- sfix17_En15
              zout => zout8  -- sfix17_En16
              );

  u_Iteration_8 : Subsystem_ip_src_CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin9),  -- sfix17_En15
              yin => std_logic_vector(yin9),  -- sfix17_En15
              zin => std_logic_vector(zin9),  -- sfix17_En16
              lut_value => std_logic_vector(lut_value9),  -- ufix16_En16
              idx => std_logic_vector(shift9),  -- ufix5
              xout => xout9,  -- sfix17_En15
              yout => yout9,  -- sfix17_En15
              zout => zout9  -- sfix17_En16
              );

  u_Iteration_9 : Subsystem_ip_src_CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin10),  -- sfix17_En15
              yin => std_logic_vector(yin10),  -- sfix17_En15
              zin => std_logic_vector(zin10),  -- sfix17_En16
              lut_value => std_logic_vector(lut_value10),  -- ufix16_En16
              idx => std_logic_vector(shift10),  -- ufix5
              xout => xout10,  -- sfix17_En15
              yout => yout10,  -- sfix17_En15
              zout => zout10  -- sfix17_En16
              );

  u_Iteration_10 : Subsystem_ip_src_CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin11),  -- sfix17_En15
              yin => std_logic_vector(yin11),  -- sfix17_En15
              zin => std_logic_vector(zin11),  -- sfix17_En16
              lut_value => std_logic_vector(lut_value11),  -- ufix16_En16
              idx => std_logic_vector(shift11),  -- ufix5
              xout => xout11,  -- sfix17_En15
              yout => yout11,  -- sfix17_En15
              zout => zout11  -- sfix17_En16
              );

  u_Iteration_11 : Subsystem_ip_src_CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin12),  -- sfix17_En15
              yin => std_logic_vector(yin12),  -- sfix17_En15
              zin => std_logic_vector(zin12),  -- sfix17_En16
              lut_value => std_logic_vector(lut_value12),  -- ufix16_En16
              idx => std_logic_vector(shift12),  -- ufix5
              xout => xout12,  -- sfix17_En15
              yout => yout12,  -- sfix17_En15
              zout => zout12  -- sfix17_En16
              );

  u_Iteration_12 : Subsystem_ip_src_CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin13),  -- sfix17_En15
              yin => std_logic_vector(yin13),  -- sfix17_En15
              zin => std_logic_vector(zin13),  -- sfix17_En16
              lut_value => std_logic_vector(lut_value13),  -- ufix16_En16
              idx => std_logic_vector(shift13),  -- ufix5
              xout => xout13,  -- sfix17_En15
              yout => yout13,  -- sfix17_En15
              zout => zout13  -- sfix17_En16
              );

  u_Iteration_13 : Subsystem_ip_src_CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin14),  -- sfix17_En15
              yin => std_logic_vector(yin14),  -- sfix17_En15
              zin => std_logic_vector(zin14),  -- sfix17_En16
              lut_value => std_logic_vector(lut_value14),  -- ufix16_En16
              idx => std_logic_vector(shift14),  -- ufix5
              xout => xout14,  -- sfix17_En15
              yout => yout14,  -- sfix17_En15
              zout => zout14  -- sfix17_En16
              );

  u_Iteration_14 : Subsystem_ip_src_CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin15),  -- sfix17_En15
              yin => std_logic_vector(yin15),  -- sfix17_En15
              zin => std_logic_vector(zin15),  -- sfix17_En16
              lut_value => std_logic_vector(lut_value15),  -- ufix16_En16
              idx => std_logic_vector(shift15),  -- ufix5
              xout => xout15,  -- sfix17_En15
              yout => yout15deadOut,  -- sfix17_En15
              zout => zout15  -- sfix17_En16
              );

  u_QuadrantCorrection : Subsystem_ip_src_Quadrant_Correction
    PORT MAP( zin => std_logic_vector(zin16),  -- sfix17_En16
              QA_Control => std_logic_vector(ControlQCDelay),  -- ufix3
              zout => zout_corrected  -- sfix19_En16
              );

  Delay_ValidIn_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_ValidIn_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_ValidIn_reg(0) <= validIn;
        Delay_ValidIn_reg(1 TO 17) <= Delay_ValidIn_reg(0 TO 16);
      END IF;
    END IF;
  END PROCESS Delay_ValidIn_process;

  ValidOutDelayed <= Delay_ValidIn_reg(17);

  reset_outval <=  NOT ValidOutDelayed;

  In_re_signed <= signed(In_re);

  qMapReal <= resize(In_re_signed, 17);

  In_im_signed <= signed(In_im);

  qMapImag <= resize(In_im_signed, 17);

  DelayRealInput_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      In1Register <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        In1Register <= qMapReal;
      END IF;
    END IF;
  END PROCESS DelayRealInput_process;


  DelayImagInput_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      In2Register <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        In2Register <= qMapImag;
      END IF;
    END IF;
  END PROCESS DelayImagInput_process;


  XQMapped_signed <= signed(XQMapped);

  yQMapped_signed <= signed(yQMapped);

  DelayQuadMapper1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin1 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin1 <= XQMapped_signed;
      END IF;
    END IF;
  END PROCESS DelayQuadMapper1_process;


  DelayQuadMapper2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin1 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin1 <= yQMapped_signed;
      END IF;
    END IF;
  END PROCESS DelayQuadMapper2_process;


  zin1 <= to_signed(16#00000#, 17);

  lut_value1 <= to_unsigned(16#76B2#, 16);

  shift1 <= to_unsigned(16#01#, 5);

  xout1_signed <= signed(xout1);

  yout1_signed <= signed(yout1);

  zout1_signed <= signed(zout1);

  Pipeline1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin2 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin2 <= xout1_signed;
      END IF;
    END IF;
  END PROCESS Pipeline1_process;


  Pipeline1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin2 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin2 <= yout1_signed;
      END IF;
    END IF;
  END PROCESS Pipeline1_1_process;


  Pipeline1_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      zin2 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        zin2 <= zout1_signed;
      END IF;
    END IF;
  END PROCESS Pipeline1_2_process;


  lut_value2 <= to_unsigned(16#3EB7#, 16);

  shift2 <= to_unsigned(16#02#, 5);

  xout2_signed <= signed(xout2);

  yout2_signed <= signed(yout2);

  zout2_signed <= signed(zout2);

  Pipeline2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin3 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin3 <= xout2_signed;
      END IF;
    END IF;
  END PROCESS Pipeline2_process;


  Pipeline2_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin3 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin3 <= yout2_signed;
      END IF;
    END IF;
  END PROCESS Pipeline2_1_process;


  Pipeline2_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      zin3 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        zin3 <= zout2_signed;
      END IF;
    END IF;
  END PROCESS Pipeline2_2_process;


  lut_value3 <= to_unsigned(16#1FD6#, 16);

  shift3 <= to_unsigned(16#03#, 5);

  xout3_signed <= signed(xout3);

  yout3_signed <= signed(yout3);

  zout3_signed <= signed(zout3);

  Pipeline3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin4 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin4 <= xout3_signed;
      END IF;
    END IF;
  END PROCESS Pipeline3_process;


  Pipeline3_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin4 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin4 <= yout3_signed;
      END IF;
    END IF;
  END PROCESS Pipeline3_1_process;


  Pipeline3_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      zin4 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        zin4 <= zout3_signed;
      END IF;
    END IF;
  END PROCESS Pipeline3_2_process;


  lut_value4 <= to_unsigned(16#0FFB#, 16);

  shift4 <= to_unsigned(16#04#, 5);

  xout4_signed <= signed(xout4);

  yout4_signed <= signed(yout4);

  zout4_signed <= signed(zout4);

  Pipeline4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin5 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin5 <= xout4_signed;
      END IF;
    END IF;
  END PROCESS Pipeline4_process;


  Pipeline4_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin5 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin5 <= yout4_signed;
      END IF;
    END IF;
  END PROCESS Pipeline4_1_process;


  Pipeline4_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      zin5 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        zin5 <= zout4_signed;
      END IF;
    END IF;
  END PROCESS Pipeline4_2_process;


  lut_value5 <= to_unsigned(16#07FF#, 16);

  shift5 <= to_unsigned(16#05#, 5);

  xout5_signed <= signed(xout5);

  yout5_signed <= signed(yout5);

  zout5_signed <= signed(zout5);

  Pipeline5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin6 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin6 <= xout5_signed;
      END IF;
    END IF;
  END PROCESS Pipeline5_process;


  Pipeline5_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin6 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin6 <= yout5_signed;
      END IF;
    END IF;
  END PROCESS Pipeline5_1_process;


  Pipeline5_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      zin6 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        zin6 <= zout5_signed;
      END IF;
    END IF;
  END PROCESS Pipeline5_2_process;


  lut_value6 <= to_unsigned(16#0400#, 16);

  shift6 <= to_unsigned(16#06#, 5);

  xout6_signed <= signed(xout6);

  yout6_signed <= signed(yout6);

  zout6_signed <= signed(zout6);

  Pipeline6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin7 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin7 <= xout6_signed;
      END IF;
    END IF;
  END PROCESS Pipeline6_process;


  Pipeline6_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin7 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin7 <= yout6_signed;
      END IF;
    END IF;
  END PROCESS Pipeline6_1_process;


  Pipeline6_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      zin7 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        zin7 <= zout6_signed;
      END IF;
    END IF;
  END PROCESS Pipeline6_2_process;


  lut_value7 <= to_unsigned(16#0200#, 16);

  shift7 <= to_unsigned(16#07#, 5);

  xout7_signed <= signed(xout7);

  yout7_signed <= signed(yout7);

  zout7_signed <= signed(zout7);

  Pipeline7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin8 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin8 <= xout7_signed;
      END IF;
    END IF;
  END PROCESS Pipeline7_process;


  Pipeline7_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin8 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin8 <= yout7_signed;
      END IF;
    END IF;
  END PROCESS Pipeline7_1_process;


  Pipeline7_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      zin8 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        zin8 <= zout7_signed;
      END IF;
    END IF;
  END PROCESS Pipeline7_2_process;


  lut_value8 <= to_unsigned(16#0100#, 16);

  shift8 <= to_unsigned(16#08#, 5);

  xout8_signed <= signed(xout8);

  yout8_signed <= signed(yout8);

  zout8_signed <= signed(zout8);

  Pipeline8_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin9 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin9 <= xout8_signed;
      END IF;
    END IF;
  END PROCESS Pipeline8_process;


  Pipeline8_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin9 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin9 <= yout8_signed;
      END IF;
    END IF;
  END PROCESS Pipeline8_1_process;


  Pipeline8_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      zin9 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        zin9 <= zout8_signed;
      END IF;
    END IF;
  END PROCESS Pipeline8_2_process;


  lut_value9 <= to_unsigned(16#0080#, 16);

  shift9 <= to_unsigned(16#09#, 5);

  xout9_signed <= signed(xout9);

  yout9_signed <= signed(yout9);

  zout9_signed <= signed(zout9);

  Pipeline9_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin10 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin10 <= xout9_signed;
      END IF;
    END IF;
  END PROCESS Pipeline9_process;


  Pipeline9_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin10 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin10 <= yout9_signed;
      END IF;
    END IF;
  END PROCESS Pipeline9_1_process;


  Pipeline9_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      zin10 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        zin10 <= zout9_signed;
      END IF;
    END IF;
  END PROCESS Pipeline9_2_process;


  lut_value10 <= to_unsigned(16#0040#, 16);

  shift10 <= to_unsigned(16#0A#, 5);

  xout10_signed <= signed(xout10);

  yout10_signed <= signed(yout10);

  zout10_signed <= signed(zout10);

  Pipeline10_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin11 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin11 <= xout10_signed;
      END IF;
    END IF;
  END PROCESS Pipeline10_process;


  Pipeline10_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin11 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin11 <= yout10_signed;
      END IF;
    END IF;
  END PROCESS Pipeline10_1_process;


  Pipeline10_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      zin11 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        zin11 <= zout10_signed;
      END IF;
    END IF;
  END PROCESS Pipeline10_2_process;


  lut_value11 <= to_unsigned(16#0020#, 16);

  shift11 <= to_unsigned(16#0B#, 5);

  xout11_signed <= signed(xout11);

  yout11_signed <= signed(yout11);

  zout11_signed <= signed(zout11);

  Pipeline11_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin12 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin12 <= xout11_signed;
      END IF;
    END IF;
  END PROCESS Pipeline11_process;


  Pipeline11_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin12 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin12 <= yout11_signed;
      END IF;
    END IF;
  END PROCESS Pipeline11_1_process;


  Pipeline11_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      zin12 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        zin12 <= zout11_signed;
      END IF;
    END IF;
  END PROCESS Pipeline11_2_process;


  lut_value12 <= to_unsigned(16#0010#, 16);

  shift12 <= to_unsigned(16#0C#, 5);

  xout12_signed <= signed(xout12);

  yout12_signed <= signed(yout12);

  zout12_signed <= signed(zout12);

  Pipeline12_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin13 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin13 <= xout12_signed;
      END IF;
    END IF;
  END PROCESS Pipeline12_process;


  Pipeline12_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin13 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin13 <= yout12_signed;
      END IF;
    END IF;
  END PROCESS Pipeline12_1_process;


  Pipeline12_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      zin13 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        zin13 <= zout12_signed;
      END IF;
    END IF;
  END PROCESS Pipeline12_2_process;


  lut_value13 <= to_unsigned(16#0008#, 16);

  shift13 <= to_unsigned(16#0D#, 5);

  xout13_signed <= signed(xout13);

  yout13_signed <= signed(yout13);

  zout13_signed <= signed(zout13);

  Pipeline13_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin14 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin14 <= xout13_signed;
      END IF;
    END IF;
  END PROCESS Pipeline13_process;


  Pipeline13_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin14 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin14 <= yout13_signed;
      END IF;
    END IF;
  END PROCESS Pipeline13_1_process;


  Pipeline13_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      zin14 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        zin14 <= zout13_signed;
      END IF;
    END IF;
  END PROCESS Pipeline13_2_process;


  lut_value14 <= to_unsigned(16#0004#, 16);

  shift14 <= to_unsigned(16#0E#, 5);

  xout14_signed <= signed(xout14);

  yout14_signed <= signed(yout14);

  zout14_signed <= signed(zout14);

  Pipeline14_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin15 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin15 <= xout14_signed;
      END IF;
    END IF;
  END PROCESS Pipeline14_process;


  Pipeline14_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin15 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin15 <= yout14_signed;
      END IF;
    END IF;
  END PROCESS Pipeline14_1_process;


  Pipeline14_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      zin15 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        zin15 <= zout14_signed;
      END IF;
    END IF;
  END PROCESS Pipeline14_2_process;


  lut_value15 <= to_unsigned(16#0002#, 16);

  shift15 <= to_unsigned(16#0F#, 5);

  xout15_signed <= signed(xout15);

  Pipeline15_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin16 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin16 <= xout15_signed;
      END IF;
    END IF;
  END PROCESS Pipeline15_process;


  -- CSD Encoding (28141) : 1001'001'00001'01'01; Cost (Adders) = 5
  CSD_Gain_Factor_mul_temp <= ((((resize(xin16 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 33) - resize(xin16 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 33)) - resize(xin16 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 33)) - resize(xin16 & '0' & '0' & '0' & '0', 33)) - resize(xin16 & '0' & '0', 33)) + resize(xin16, 33);
  CSD_Gain_Factor_cast <= CSD_Gain_Factor_mul_temp(31 DOWNTO 0);
  xoutscaled <= CSD_Gain_Factor_cast(31 DOWNTO 15);

  zeroC <= to_signed(16#00000#, 17);

  
  outSwitchMag <= xoutscaled WHEN reset_outval = '0' ELSE
      zeroC;

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin17 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin17 <= outSwitchMag;
      END IF;
    END IF;
  END PROCESS Output_Register_process;


  magnitude <= std_logic_vector(xin17);

  zout15_signed <= signed(zout15);

  ControlQC_unsigned <= unsigned(ControlQC);

  Pipeline15_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      zin16 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        zin16 <= zout15_signed;
      END IF;
    END IF;
  END PROCESS Pipeline15_1_process;


  DelayQC_Control_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      DelayQC_Control_reg <= (OTHERS => to_unsigned(16#0#, 3));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        DelayQC_Control_reg(0) <= ControlQC_unsigned;
        DelayQC_Control_reg(1 TO 15) <= DelayQC_Control_reg(0 TO 14);
      END IF;
    END IF;
  END PROCESS DelayQC_Control_process;

  ControlQCDelay <= DelayQC_Control_reg(15);

  zout_corrected_signed <= signed(zout_corrected);

  zeroCA <= to_signed(16#00000#, 19);

  
  outSwitchAng <= zout_corrected_signed WHEN reset_outval = '0' ELSE
      zeroCA;

  Output_Register_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      zout_corrected_1 <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        zout_corrected_1 <= outSwitchAng;
      END IF;
    END IF;
  END PROCESS Output_Register_1_process;


  angle <= std_logic_vector(zout_corrected_1);

  DelayValidOut_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      validOut <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        validOut <= ValidOutDelayed;
      END IF;
    END IF;
  END PROCESS DelayValidOut_process;


END rtl;

