function gs_newsimul_setup(hFPGA)
%--------------------------------------------------------------------------
% Host Interface Script Setup
% 
% Generated with MATLAB 9.14 (R2023a) at 13:22:53 on 25/04/2023.
% This function was created for the IP Core generated from design 'newsimul'.
% 
% Run this function on an "fpga" object to configure it with the same interfaces as the generated IP core.
%--------------------------------------------------------------------------

%% AXI4-Lite
addAXI4SlaveInterface(hFPGA, ...
	"InterfaceID", "AXI4-Lite", ...
	"BaseAddress", 0x40010000, ...
	"AddressRange", 0x10000);

DUTPort_datareal = hdlcoder.DUTPort("datareal", ...
	"Direction", "IN", ...
	"DataType", numerictype(1,16,15), ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x100");

DUTPort_dataimag = hdlcoder.DUTPort("dataimag", ...
	"Direction", "IN", ...
	"DataType", numerictype(1,16,15), ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x104");

DUTPort_amp = hdlcoder.DUTPort("amp", ...
	"Direction", "OUT", ...
	"DataType", numerictype(1,17,15), ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x108");

DUTPort_angle = hdlcoder.DUTPort("angle", ...
	"Direction", "OUT", ...
	"DataType", numerictype(1,19,16), ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x10C");

DUTPort_vaild = hdlcoder.DUTPort("vaild", ...
	"Direction", "OUT", ...
	"DataType", "logical", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x110");

mapPort(hFPGA, [DUTPort_datareal, DUTPort_dataimag, DUTPort_amp, DUTPort_angle, DUTPort_vaild]);

end
