-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\newsimul\Subsystem_ip_src_Quadrant_Correction.vhd
-- Created: 2023-04-25 13:19:39
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem_ip_src_Quadrant_Correction
-- Source Path: newsimul/Subsystem/Subsystem1/HDL_CMA_core/Quadrant_Correction
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Subsystem_ip_src_Quadrant_Correction IS
  PORT( zin                               :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En16
        QA_Control                        :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
        zout                              :   OUT   std_logic_vector(18 DOWNTO 0)  -- sfix19_En16
        );
END Subsystem_ip_src_Quadrant_Correction;


ARCHITECTURE rtl OF Subsystem_ip_src_Quadrant_Correction IS

  -- Signals
  SIGNAL QA_Control_unsigned              : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL xyNegative                       : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL AbsRel                           : std_logic;  -- ufix1
  SIGNAL pidivtwo                         : signed(18 DOWNTO 0);  -- sfix19_En16
  SIGNAL zin_signed                       : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL zCast                            : signed(18 DOWNTO 0);  -- sfix19_En16
  SIGNAL pivdivtwosubout                  : signed(18 DOWNTO 0);  -- sfix19_En16
  SIGNAL mux1out                          : signed(18 DOWNTO 0);  -- sfix19_En16
  SIGNAL Negation_cast                    : signed(19 DOWNTO 0);  -- sfix20_En16
  SIGNAL Negation_cast_1                  : signed(19 DOWNTO 0);  -- sfix20_En16
  SIGNAL Negation_cast_2                  : signed(20 DOWNTO 0);  -- sfix21_En16
  SIGNAL mux1out_negate                   : signed(18 DOWNTO 0);  -- sfix19_En16
  SIGNAL pionepos                         : signed(18 DOWNTO 0);  -- sfix19_En16
  SIGNAL pi_subtraction                   : signed(18 DOWNTO 0);  -- sfix19_En16
  SIGNAL pioneneg                         : signed(18 DOWNTO 0);  -- sfix19_En16
  SIGNAL negpi_addition                   : signed(18 DOWNTO 0);  -- sfix19_En16
  SIGNAL mux2out                          : signed(18 DOWNTO 0);  -- sfix19_En16

BEGIN
  QA_Control_unsigned <= unsigned(QA_Control);

  xyNegative <= QA_Control_unsigned(1 DOWNTO 0);

  AbsRel <= QA_Control_unsigned(2);

  pidivtwo <= to_signed(16#1921F#, 19);

  zin_signed <= signed(zin);

  zCast <= resize(zin_signed, 19);

  pivdivtwosubout <= pidivtwo - zCast;

  
  mux1out <= pivdivtwosubout WHEN AbsRel = '0' ELSE
      zCast;

  Negation_cast <= resize(mux1out, 20);
  Negation_cast_1 <=  - (Negation_cast);
  Negation_cast_2 <= resize(Negation_cast_1, 21);
  mux1out_negate <= Negation_cast_2(18 DOWNTO 0);

  pionepos <= to_signed(16#3243F#, 19);

  pi_subtraction <= pionepos - mux1out;

  pioneneg <= to_signed(-16#32440#, 19);

  negpi_addition <= pioneneg + mux1out;

  
  mux2out <= mux1out WHEN xyNegative = to_unsigned(16#0#, 2) ELSE
      mux1out_negate WHEN xyNegative = to_unsigned(16#1#, 2) ELSE
      pi_subtraction WHEN xyNegative = to_unsigned(16#2#, 2) ELSE
      negpi_addition;

  zout <= std_logic_vector(mux2out);

END rtl;

