-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\newsimul\Subsystem_ip_addr_decoder.vhd
-- Created: 2023-04-25 13:19:48
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem_ip_addr_decoder
-- Source Path: Subsystem_ip/Subsystem_ip_axi_lite/Subsystem_ip_addr_decoder
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Subsystem_ip_addr_decoder IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        data_write                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        addr_sel                          :   IN    std_logic_vector(13 DOWNTO 0);  -- ufix14
        wr_enb                            :   IN    std_logic;  -- ufix1
        rd_enb                            :   IN    std_logic;  -- ufix1
        read_ip_timestamp                 :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        read_amp                          :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En15
        read_angle                        :   IN    std_logic_vector(18 DOWNTO 0);  -- sfix19_En16
        read_vaild                        :   IN    std_logic;  -- ufix1
        data_read                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        write_axi_enable                  :   OUT   std_logic;  -- ufix1
        write_datareal                    :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        write_dataimag                    :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
        );
END Subsystem_ip_addr_decoder;


ARCHITECTURE rtl OF Subsystem_ip_addr_decoder IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL addr_sel_unsigned                : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL decode_sel_ip_timestamp_1_1      : std_logic;  -- ufix1
  SIGNAL const_0                          : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_ip_timestamp_unsigned       : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL const_1_1                        : std_logic;  -- ufix1
  SIGNAL read_amp_signed                  : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL read_angle_signed                : signed(18 DOWNTO 0);  -- sfix19_En16
  SIGNAL decode_sel_vaild_1_1             : std_logic;  -- ufix1
  SIGNAL decode_sel_angle_1_1             : std_logic;  -- ufix1
  SIGNAL decode_sel_amp_1_1               : std_logic;  -- ufix1
  SIGNAL read_reg_ip_timestamp            : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_ip_timestamp_1_1       : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_reg_amp                     : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL data_slice_amp_1                 : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_amp_1_1                : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_reg_angle                   : signed(18 DOWNTO 0);  -- sfix19_En16
  SIGNAL data_slice_angle_1               : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_angle_1_1              : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_reg_vaild                   : std_logic;  -- ufix1
  SIGNAL data_slice_vaild_1               : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_vaild_1_1              : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_sel_axi_enable_1_1        : std_logic;  -- ufix1
  SIGNAL reg_enb_axi_enable_1_1           : std_logic;  -- ufix1
  SIGNAL data_write_unsigned              : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL data_in_axi_enable               : std_logic;  -- ufix1
  SIGNAL data_reg_axi_enable_1_1          : std_logic;  -- ufix1
  SIGNAL decode_sel_datareal_1_1          : std_logic;  -- ufix1
  SIGNAL reg_enb_datareal_1_1             : std_logic;  -- ufix1
  SIGNAL data_in_datareal                 : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL data_reg_datareal_1_1            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL decode_sel_dataimag_1_1          : std_logic;  -- ufix1
  SIGNAL reg_enb_dataimag_1_1             : std_logic;  -- ufix1
  SIGNAL data_in_dataimag                 : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL data_reg_dataimag_1_1            : signed(15 DOWNTO 0);  -- sfix16_En15

BEGIN
  addr_sel_unsigned <= unsigned(addr_sel);

  
  decode_sel_ip_timestamp_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0002#, 14) ELSE
      '0';

  const_0 <= to_unsigned(0, 32);

  read_ip_timestamp_unsigned <= unsigned(read_ip_timestamp);

  const_1_1 <= '1';

  enb <= const_1_1;

  read_amp_signed <= signed(read_amp);

  read_angle_signed <= signed(read_angle);

  
  decode_sel_vaild_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0044#, 14) ELSE
      '0';

  
  decode_sel_angle_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0043#, 14) ELSE
      '0';

  
  decode_sel_amp_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0042#, 14) ELSE
      '0';

  reg_ip_timestamp_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      read_reg_ip_timestamp <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        read_reg_ip_timestamp <= read_ip_timestamp_unsigned;
      END IF;
    END IF;
  END PROCESS reg_ip_timestamp_process;


  
  decode_rd_ip_timestamp_1_1 <= const_0 WHEN decode_sel_ip_timestamp_1_1 = '0' ELSE
      read_reg_ip_timestamp;

  reg_amp_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      read_reg_amp <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        read_reg_amp <= read_amp_signed;
      END IF;
    END IF;
  END PROCESS reg_amp_process;


  data_slice_amp_1 <= unsigned(resize(read_reg_amp, 32));

  
  decode_rd_amp_1_1 <= decode_rd_ip_timestamp_1_1 WHEN decode_sel_amp_1_1 = '0' ELSE
      data_slice_amp_1;

  reg_angle_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      read_reg_angle <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        read_reg_angle <= read_angle_signed;
      END IF;
    END IF;
  END PROCESS reg_angle_process;


  data_slice_angle_1 <= unsigned(resize(read_reg_angle, 32));

  
  decode_rd_angle_1_1 <= decode_rd_amp_1_1 WHEN decode_sel_angle_1_1 = '0' ELSE
      data_slice_angle_1;

  reg_vaild_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      read_reg_vaild <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        read_reg_vaild <= read_vaild;
      END IF;
    END IF;
  END PROCESS reg_vaild_process;


  data_slice_vaild_1 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & read_reg_vaild;

  
  decode_rd_vaild_1_1 <= decode_rd_angle_1_1 WHEN decode_sel_vaild_1_1 = '0' ELSE
      data_slice_vaild_1;

  data_read <= std_logic_vector(decode_rd_vaild_1_1);

  
  decode_sel_axi_enable_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0001#, 14) ELSE
      '0';

  reg_enb_axi_enable_1_1 <= decode_sel_axi_enable_1_1 AND wr_enb;

  data_write_unsigned <= unsigned(data_write);

  data_in_axi_enable <= data_write_unsigned(0);

  reg_axi_enable_1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      data_reg_axi_enable_1_1 <= '1';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_axi_enable_1_1 = '1' THEN
        data_reg_axi_enable_1_1 <= data_in_axi_enable;
      END IF;
    END IF;
  END PROCESS reg_axi_enable_1_1_process;


  
  decode_sel_datareal_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0040#, 14) ELSE
      '0';

  reg_enb_datareal_1_1 <= decode_sel_datareal_1_1 AND wr_enb;

  data_in_datareal <= signed(data_write_unsigned(15 DOWNTO 0));

  reg_datareal_1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      data_reg_datareal_1_1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_datareal_1_1 = '1' THEN
        data_reg_datareal_1_1 <= data_in_datareal;
      END IF;
    END IF;
  END PROCESS reg_datareal_1_1_process;


  write_datareal <= std_logic_vector(data_reg_datareal_1_1);

  
  decode_sel_dataimag_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0041#, 14) ELSE
      '0';

  reg_enb_dataimag_1_1 <= decode_sel_dataimag_1_1 AND wr_enb;

  data_in_dataimag <= signed(data_write_unsigned(15 DOWNTO 0));

  reg_dataimag_1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      data_reg_dataimag_1_1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_dataimag_1_1 = '1' THEN
        data_reg_dataimag_1_1 <= data_in_dataimag;
      END IF;
    END IF;
  END PROCESS reg_dataimag_1_1_process;


  write_dataimag <= std_logic_vector(data_reg_dataimag_1_1);

  write_axi_enable <= data_reg_axi_enable_1_1;

END rtl;

