-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\newsimul\Subsystem_ip_src_Subsystem1.vhd
-- Created: 2023-04-25 13:19:39
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem_ip_src_Subsystem1
-- Source Path: newsimul/Subsystem/Subsystem1
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Subsystem_ip_src_Subsystem1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Indata_re                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        Indata_im                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        amp                               :   OUT   std_logic_vector(16 DOWNTO 0);  -- sfix17_En15
        angle                             :   OUT   std_logic_vector(18 DOWNTO 0);  -- sfix19_En16
        vaild                             :   OUT   std_logic
        );
END Subsystem_ip_src_Subsystem1;


ARCHITECTURE rtl OF Subsystem_ip_src_Subsystem1 IS

  -- Component Declarations
  COMPONENT Subsystem_ip_src_HDL_CMA_core
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In_re                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          In_im                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          validIn                         :   IN    std_logic;
          magnitude                       :   OUT   std_logic_vector(16 DOWNTO 0);  -- sfix17_En15
          angle                           :   OUT   std_logic_vector(18 DOWNTO 0);  -- sfix19_En16
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Subsystem_ip_src_HDL_CMA_core
    USE ENTITY work.Subsystem_ip_src_HDL_CMA_core(rtl);

  -- Signals
  SIGNAL Constant_out1                    : std_logic;
  SIGNAL Complex_to_Magnitude_Angle1_out1 : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL Complex_to_Magnitude_Angle1_out2 : std_logic_vector(18 DOWNTO 0);  -- ufix19
  SIGNAL Complex_to_Magnitude_Angle1_out3 : std_logic;

BEGIN
  u_Complex_to_Magnitude_Angle1 : Subsystem_ip_src_HDL_CMA_core
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In_re => Indata_re,  -- sfix16_En15
              In_im => Indata_im,  -- sfix16_En15
              validIn => Constant_out1,
              magnitude => Complex_to_Magnitude_Angle1_out1,  -- sfix17_En15
              angle => Complex_to_Magnitude_Angle1_out2,  -- sfix19_En16
              validOut => Complex_to_Magnitude_Angle1_out3
              );

  Constant_out1 <= '1';

  amp <= Complex_to_Magnitude_Angle1_out1;

  angle <= Complex_to_Magnitude_Angle1_out2;

  vaild <= Complex_to_Magnitude_Angle1_out3;

END rtl;

